# Generated by Django 6.0.3 on 2026-03-29 22:31

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Author name")),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Category name")),
            ],
        ),
        migrations.CreateModel(
            name="AuthorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("bio", models.TextField(blank=True, default="", verbose_name="Biography")),
                (
                    "author",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="sample.author",
                        verbose_name="Author",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FieldShowcase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("char_f", models.CharField(blank=True, default="", max_length=50)),
                ("text_f", models.TextField(blank=True, default="")),
                ("slug_f", models.SlugField(blank=True, default="")),
                ("email_f", models.EmailField(blank=True, default="", max_length=254)),
                ("url_f", models.URLField(blank=True, default="")),
                ("int_f", models.IntegerField(blank=True, null=True)),
                ("bigint_f", models.BigIntegerField(blank=True, null=True)),
                ("smallint_f", models.SmallIntegerField(blank=True, null=True)),
                ("posint_f", models.PositiveIntegerField(blank=True, null=True)),
                ("possmall_f", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("posbigint_f", models.PositiveBigIntegerField(blank=True, null=True)),
                ("float_f", models.FloatField(blank=True, null=True)),
                (
                    "decimal_f",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("bool_f", models.BooleanField(default=False)),
                ("bool_null_f", models.BooleanField(blank=True, null=True)),
                ("date_f", models.DateField(blank=True, null=True)),
                ("datetime_f", models.DateTimeField(blank=True, null=True)),
                ("time_f", models.TimeField(blank=True, null=True)),
                ("duration_f", models.DurationField(blank=True, null=True)),
                ("uuid_f", models.UUIDField(blank=True, null=True)),
                ("binary_f", models.BinaryField(blank=True, null=True)),
                ("json_f", models.JSONField(blank=True, default=dict)),
                ("ip_f", models.GenericIPAddressField(blank=True, null=True)),
                ("file_f", models.FileField(blank=True, null=True, upload_to="sample_fc/")),
                (
                    "fk_author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_showcases",
                        to="sample.author",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FieldShowcaseDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=100)),
                (
                    "showcase",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail",
                        to="sample.fieldshowcase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GenericBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("label", models.CharField(blank=True, default="", max_length=50)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Tag label")),
                (
                    "importance",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Importance"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tags",
                        to="sample.category",
                        verbose_name="Category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fieldshowcase",
            name="tags_m2m",
            field=models.ManyToManyField(
                blank=True, related_name="field_showcases", to="sample.tag"
            ),
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Book title")),
                ("pages", models.PositiveIntegerField(default=0, verbose_name="Nb. of pages")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Price"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Extra metadata"),
                ),
                (
                    "publication_date",
                    models.DateField(default=datetime.date.today, verbose_name="Publication date"),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Recorded at"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sample.author",
                        verbose_name="Author",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="books", to="sample.tag", verbose_name="Tags"
                    ),
                ),
            ],
        ),
    ]
