# Generated by Django 6.0.3 on 2026-04-11 14:15

import django.db.models.deletion
import django_boosted.models.fields
import namedid.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportDefinition',
            fields=[
                ('created_by', django_boosted.models.fields.AuditUserField(blank=True, default=None, editable=False, max_length=255, mode='created', null=True)),
                ('updated_by', django_boosted.models.fields.AuditUserField(blank=True, default=None, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('named_id', namedid.fields.NamedIDField(blank=False, max_length=255, null=False, source_fields=['name'], unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional.', null=True, verbose_name='Description')),
                ('manager', models.CharField(default='objects.all', help_text='Default: objects.all', max_length=255, verbose_name='Manager')),
                ('manager_kwargs_config', models.JSONField(blank=True, default=dict, help_text='Static ORM kwargs merged via QuerySet.filter() immediately after the manager path resolves, before filter_config / filter_request.', null=True, verbose_name='Manager filter (static)')),
                ('manager_kwargs_request', models.JSONField(blank=True, default=dict, help_text='Same shape as request filters: {query_param: orm_lookup}. Values come from the export form as mg_get_<param> (optional unless listed in manager_kwargs_mandatory).', null=True, verbose_name='Manager request filters')),
                ('manager_kwargs_mandatory', models.JSONField(blank=True, default=dict, help_text='Same shape as mandatory filters (GET and/or kwargs). Form keys mg_get_* / mg_kw_*.', null=True, verbose_name='Manager mandatory filters')),
                ('order_by', models.JSONField(blank=True, default=list, help_text='List of field names for QuerySet.order_by, e.g. ["title", "-pages"]. Use a leading minus for descending. Empty = model default.', null=True, verbose_name='Order by')),
                ('filter_config', models.JSONField(blank=True, default=dict, help_text="Static filters. example: {'id': 1}", null=True, verbose_name='Filter configuration')),
                ('filter_request', models.JSONField(blank=True, default=dict, help_text='JSON object {query_param: orm_lookup}. Left: name in request.GET (e.g. ?before=…). Right: Django filter kwarg for the target model (field or field__lookup). Example: {"before": "recorded_at__lt", "max_id": "id__lt"}. Do not put ORM lookups on the left or a short alias like “date” on the right.', null=True, verbose_name='Request filters')),
                ('filter_mandatory', models.JSONField(blank=True, default=dict, help_text='Either shorthand GET-only mapping, e.g. {"author_id": "author__id"}, or an object with “get” and/or “kwargs”: query param names or URL path names → ORM filter keys. All listed values must be present (request.GET and url kwargs). Example: {"kwargs": {"group_id": "group_id"}} for …/group/<group_id>/', null=True, verbose_name='Mandatory filters')),
                ('max_relation_hops', models.PositiveIntegerField(blank=True, help_text='Maximum depth when traversing relations for table columns. Use 0 for top-level fields only. Leave empty for no limit.', null=True, verbose_name='Max relation hops')),
                ('exclude_relations', models.ManyToManyField(blank=True, help_text='Content types whose relations should never be traversed when building export or import column paths (e.g. auth.User).', related_name='excluded_from_exports', to='contenttypes.contenttype', verbose_name='Exclude relations')),
                ('target', models.ForeignKey(blank=True, help_text='Listed model.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='django_importexport_flow_targeted', to='contenttypes.contenttype', verbose_name='Target content type')),
            ],
            options={
                'verbose_name': 'Export definition',
                'verbose_name_plural': 'Export definitions',
                'db_table': 'django_reportimport_reportdefinition',
                'ordering': ('name', 'target'),
            },
        ),
        migrations.CreateModel(
            name='ExportConfigPdf',
            fields=[
                ('export', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='config_pdf', serialize=False, to='django_importexport_flow.exportdefinition', verbose_name='Export')),
                ('template', models.TextField(blank=True, help_text='HTML template.', null=True, verbose_name='Template')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Renderer options.', null=True, verbose_name='Configuration')),
            ],
            options={
                'verbose_name': 'Export PDF configuration',
                'verbose_name_plural': 'Export PDF configurations',
                'db_table': 'django_reportimport_reportconfigpdf',
            },
        ),
        migrations.CreateModel(
            name='ExportConfigTable',
            fields=[
                ('export', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='config_table', serialize=False, to='django_importexport_flow.exportdefinition', verbose_name='Export')),
                ('columns', models.JSONField(blank=True, default=list, help_text='List of strings: each is a field path (e.g. author.name), keys inside a ``JSONField`` (e.g. metadata.lang), an ``@property`` / ``cached_property`` on the model or a related model (e.g. author.name_upper), an expand spec: relation.*[field1:field2] for one-to-many relations, or a queryset annotation name declared in ``configuration`` (``annotation_columns``, ``annotations``).', null=True, verbose_name='Columns')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Export options passed to pandas: keys ``csv``, ``excel``, ``json`` (see DataFrame.to_csv, to_excel, to_json). Default JSON uses orient=records. Optional ``annotation_columns``: list of names added only by ``QuerySet.annotate()`` (not ORM fields, JSON subpaths, or properties) so they may appear in ``columns``. For any column path in ``columns`` with no ORM verbose name (annotations, unknown paths, …), you may set ``<path>_label`` to the header text, e.g. ``author.total_books_label`` for path ``author.total_books``; for expand subfields, use ``<subfield>_label`` (e.g. ``pages_label``).', null=True, verbose_name='Configuration')),
            ],
            options={
                'verbose_name': 'Export table configuration',
                'verbose_name_plural': 'Export table configurations',
                'db_table': 'django_reportimport_reportconfigtable',
            },
        ),
        migrations.CreateModel(
            name='ExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', django_boosted.models.fields.AuditUserField(blank=True, default=None, editable=False, max_length=255, mode='created', null=True)),
                ('updated_by', django_boosted.models.fields.AuditUserField(blank=True, default=None, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('export_format', models.CharField(blank=True, help_text='csv, excel, or json.', max_length=16, verbose_name='Export format')),
                ('filter_payload', models.JSONField(blank=True, default=dict, help_text='export_format plus fr_get_* / fr_kw_* from the export form.', verbose_name='Filter form payload')),
                ('manager_kwargs_payload', models.JSONField(blank=True, default=dict, help_text='mg_get_* / mg_kw_* from the export form (manager_kwargs_* on the definition).', verbose_name='Manager kwargs form payload')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=16, verbose_name='Status')),
                ('output_bytes', models.PositiveIntegerField(blank=True, help_text='Set when export completed successfully.', null=True, verbose_name='Output size (bytes)')),
                ('error_trace', models.TextField(blank=True, help_text='Message or traceback when status is failure.', verbose_name='Error trace')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('export_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_requests', to='django_importexport_flow.exportdefinition', verbose_name='Export definition')),
                ('initiated_by', models.ForeignKey(blank=True, help_text='User who ran the export in the admin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_export_requests', to=settings.AUTH_USER_MODEL, verbose_name='Initiated by')),
            ],
            options={
                'verbose_name': 'Export request',
                'verbose_name_plural': 'Export requests',
                'db_table': 'django_reportimport_reportrequest',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ExportRequestRelatedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(help_text='Primary key as string (integer or UUID).', max_length=64, verbose_name='Object id')),
                ('object_str', models.CharField(blank=True, default='', editable=False, help_text='Snapshot when saved; kept if the related row is deleted.', max_length=500, verbose_name='Object representation')),
                ('content_type', models.ForeignKey(help_text='Model of the related instance.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content type')),
                ('export_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_object_links', to='django_importexport_flow.exportrequest', verbose_name='Export request')),
            ],
            options={
                'verbose_name': 'Export request related object',
                'verbose_name_plural': 'Export request related objects',
            },
        ),
        migrations.CreateModel(
            name='ImportDefinition',
            fields=[
                ('created_by', django_boosted.models.fields.AuditUserField(blank=True, default=None, editable=False, max_length=255, mode='created', null=True)),
                ('updated_by', django_boosted.models.fields.AuditUserField(blank=True, default=None, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('named_id', namedid.fields.NamedIDField(blank=False, max_length=255, null=False, source_fields=['name'], unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional.', null=True, verbose_name='Description')),
                ('order_by', models.JSONField(blank=True, default=list, help_text='List of field names for QuerySet.order_by, e.g. ["title", "-pages"]. Empty = model default ordering.', null=True, verbose_name='Order by')),
                ('filter_config', models.JSONField(blank=True, default=dict, help_text="Static queryset filters (e.g. tenant or scope). example: {'tenant_id': 1}", null=True, verbose_name='Filter configuration')),
                ('filter_request', models.JSONField(blank=True, default=dict, help_text='JSON {query_param: orm_lookup}. Left = GET name (?before=…); right = filter key on the target model, e.g. "recorded_at__lt", "id__lt".', null=True, verbose_name='Request filters')),
                ('filter_mandatory', models.JSONField(blank=True, default=dict, help_text='Optional shorthand GET map, e.g. {"tenant_id": "tenant_id"}, or {"get": {...}, "kwargs": {...}} for required query params and URL path kwargs.', null=True, verbose_name='Mandatory filters')),
                ('columns_exclude', models.JSONField(blank=True, default=list, help_text='Field paths to omit from import and from the example file. All other importable columns (top-level scalars and one FK level) are used. If a path is a forward relation (FK/O2O), all nested paths under that relation are excluded as well (e.g. author → author.name). Reverse-expand specs are not part of the default set.', null=True, verbose_name='Columns exclude')),
                ('exclude_primary_key', models.BooleanField(default=True, help_text='When enabled, the target model’s primary key field is omitted from the default column set (in addition to columns exclude).', verbose_name='Exclude primary key')),
                ('max_relation_hops', models.PositiveIntegerField(blank=True, db_column='import_max_relation_hops', help_text='Maximum number of relation hops in generated import paths (nested FKs, M2M slot paths such as tags.0.category.name). Use 0 for no nested relation paths (top-level columns only). Leave empty for no limit (a high internal cap applies).', null=True, verbose_name='Max relation hops')),
                ('match_fields', models.JSONField(blank=True, db_column='import_match_fields', default=list, help_text='Optional list of target model field names used to find existing rows before updating (e.g. ["email"] for users). Empty = always create new rows. Values from static filters (filter_config) and request filters are added to the lookup automatically so imports stay scoped. Each row must provide non-empty values for every match field.', null=True, verbose_name='Match fields')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Export options.', null=True, verbose_name='Configuration')),
                ('exclude_relations', models.ManyToManyField(blank=True, help_text='Content types whose relations should never be traversed when building import column paths (e.g. auth.User).', related_name='excluded_from_imports', to='contenttypes.contenttype', verbose_name='Exclude relations')),
                ('target', models.ForeignKey(blank=True, help_text='Listed model.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='django_importexport_flow_import_targeted', to='contenttypes.contenttype', verbose_name='Target content type')),
            ],
            options={
                'verbose_name': 'Import definition',
                'verbose_name_plural': 'Import definitions',
                'db_table': 'django_reporting_reportimport',
                'ordering': ('name', 'target'),
            },
        ),
        migrations.CreateModel(
            name='ImportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', django_boosted.models.fields.AuditUserField(blank=True, default=None, editable=False, max_length=255, mode='created', null=True)),
                ('updated_by', django_boosted.models.fields.AuditUserField(blank=True, default=None, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('data_file', models.FileField(upload_to='report_import_asks/%Y/%m/', verbose_name='Uploaded file')),
                ('filter_payload', models.JSONField(blank=True, default=dict, help_text='Keys fr_get_* / fr_kw_* from the import wizard.', verbose_name='Filter form payload')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=16, verbose_name='Status')),
                ('imported_row_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Imported row count')),
                ('error_trace', models.TextField(blank=True, help_text='Traceback or per-row errors when status is failure.', verbose_name='Error trace')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('import_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_requests', to='django_importexport_flow.importdefinition', verbose_name='Import definition')),
                ('initiated_by', models.ForeignKey(blank=True, help_text='User who started the import (wizard or relaunch).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_requests', to=settings.AUTH_USER_MODEL, verbose_name='Initiated by')),
                ('relaunched_from', models.ForeignKey(blank=True, help_text='Previous request when this row was created by “Relaunch”.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relaunches', to='django_importexport_flow.importrequest', verbose_name='Relaunched from')),
            ],
            options={
                'verbose_name': 'Import request',
                'verbose_name_plural': 'Import requests',
                'db_table': 'django_reporting_reportimportask',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ImportRequestRelatedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(help_text='Primary key as string (integer or UUID).', max_length=64, verbose_name='Object id')),
                ('object_str', models.CharField(blank=True, default='', editable=False, help_text='Snapshot when saved; kept if the related row is deleted.', max_length=500, verbose_name='Object representation')),
                ('content_type', models.ForeignKey(help_text='Model of the related instance.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content type')),
                ('import_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_object_links', to='django_importexport_flow.importrequest', verbose_name='Import request')),
            ],
            options={
                'verbose_name': 'Import request related object',
                'verbose_name_plural': 'Import request related objects',
            },
        ),
    ]
