# Generated by Django 6.0.3 on 2026-03-29 22:31

import django.db.models.deletion
import django_boosted.models.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportDefinition',
            fields=[
                ('created_by', django_boosted.models.fields.AuditUserField(blank=True, default=None, editable=False, max_length=255, mode='created', null=True)),
                ('updated_by', django_boosted.models.fields.AuditUserField(blank=True, default=None, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Optional.', null=True, verbose_name='Description')),
                ('manager', models.CharField(default='objects.all', help_text='Default: objects.all', max_length=255, verbose_name='Manager')),
                ('order_by', models.JSONField(blank=True, default=list, help_text='List of field names for QuerySet.order_by, e.g. ["title", "-pages"]. Use a leading minus for descending. Empty = model default.', null=True, verbose_name='Order by')),
                ('filter_config', models.JSONField(blank=True, default=dict, help_text="Static filters. example: {'id': 1}", null=True, verbose_name='Filter configuration')),
                ('filter_request', models.JSONField(blank=True, default=dict, help_text='JSON object {query_param: orm_lookup}. Left: name in request.GET (e.g. ?before=…). Right: Django filter kwarg for the target model (field or field__lookup). Example: {"before": "recorded_at__lt", "max_id": "id__lt"}. Do not put ORM lookups on the left or a short alias like “date” on the right.', null=True, verbose_name='Request filters')),
                ('filter_mandatory', models.JSONField(blank=True, default=dict, help_text='Either shorthand GET-only mapping, e.g. {"author_id": "author__id"}, or an object with “get” and/or “kwargs”: query param names or URL path names → ORM filter keys. All listed values must be present (request.GET and url kwargs). Example: {"kwargs": {"group_id": "group_id"}} for …/group/<group_id>/', null=True, verbose_name='Mandatory filters')),
                ('target', models.ForeignKey(blank=True, help_text='Listed model.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='django_importexport_flow_targeted', to='contenttypes.contenttype', verbose_name='Target content type')),
            ],
            options={
                'verbose_name': 'Export definition',
                'verbose_name_plural': 'Export definitions',
                'db_table': 'django_reportimport_reportdefinition',
                'ordering': ('name', 'target'),
            },
        ),
        migrations.CreateModel(
            name='ExportConfigPdf',
            fields=[
                ('export', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='config_pdf', serialize=False, to='django_importexport_flow.exportdefinition', verbose_name='Export')),
                ('template', models.TextField(blank=True, help_text='HTML template.', null=True, verbose_name='Template')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Renderer options.', null=True, verbose_name='Configuration')),
            ],
            options={
                'verbose_name': 'Export PDF configuration',
                'verbose_name_plural': 'Export PDF configurations',
                'db_table': 'django_reportimport_reportconfigpdf',
            },
        ),
        migrations.CreateModel(
            name='ExportConfigTable',
            fields=[
                ('export', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='config_table', serialize=False, to='django_importexport_flow.exportdefinition', verbose_name='Export')),
                ('columns', models.JSONField(blank=True, default=list, help_text='List of strings: each is a field path (e.g. author.name) or an expand spec: relation.*[field1:field2] for one-to-many relations.', null=True, verbose_name='Columns')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Export options passed to pandas: keys ``csv``, ``excel``, ``json`` (see DataFrame.to_csv, to_excel, to_json). Default JSON uses orient=records.', null=True, verbose_name='Configuration')),
            ],
            options={
                'verbose_name': 'Export table configuration',
                'verbose_name_plural': 'Export table configurations',
                'db_table': 'django_reportimport_reportconfigtable',
            },
        ),
        migrations.CreateModel(
            name='ExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', django_boosted.models.fields.AuditUserField(blank=True, default=None, editable=False, max_length=255, mode='created', null=True)),
                ('updated_by', django_boosted.models.fields.AuditUserField(blank=True, default=None, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('export_format', models.CharField(blank=True, help_text='csv, excel, or json.', max_length=16, verbose_name='Export format')),
                ('filter_payload', models.JSONField(blank=True, default=dict, help_text='export_format plus fr_get_* / fr_kw_* from the export form.', verbose_name='Filter form payload')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=16, verbose_name='Status')),
                ('output_bytes', models.PositiveIntegerField(blank=True, help_text='Set when export completed successfully.', null=True, verbose_name='Output size (bytes)')),
                ('error_trace', models.TextField(blank=True, help_text='Message or traceback when status is failure.', verbose_name='Error trace')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('export_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_requests', to='django_importexport_flow.exportdefinition', verbose_name='Export definition')),
                ('initiated_by', models.ForeignKey(blank=True, help_text='User who ran the export in the admin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_export_requests', to=settings.AUTH_USER_MODEL, verbose_name='Initiated by')),
            ],
            options={
                'verbose_name': 'Export request',
                'verbose_name_plural': 'Export requests',
                'db_table': 'django_reportimport_reportrequest',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ImportDefinition',
            fields=[
                ('created_by', django_boosted.models.fields.AuditUserField(blank=True, default=None, editable=False, max_length=255, mode='created', null=True)),
                ('updated_by', django_boosted.models.fields.AuditUserField(blank=True, default=None, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Optional.', null=True, verbose_name='Description')),
                ('order_by', models.JSONField(blank=True, default=list, help_text='List of field names for QuerySet.order_by, e.g. ["title", "-pages"]. Empty = model default ordering.', null=True, verbose_name='Order by')),
                ('filter_config', models.JSONField(blank=True, default=dict, help_text="Static queryset filters (e.g. tenant or scope). example: {'tenant_id': 1}", null=True, verbose_name='Filter configuration')),
                ('filter_request', models.JSONField(blank=True, default=dict, help_text='JSON {query_param: orm_lookup}. Left = GET name (?before=…); right = filter key on the target model, e.g. "recorded_at__lt", "id__lt".', null=True, verbose_name='Request filters')),
                ('filter_mandatory', models.JSONField(blank=True, default=dict, help_text='Optional shorthand GET map, e.g. {"tenant_id": "tenant_id"}, or {"get": {...}, "kwargs": {...}} for required query params and URL path kwargs.', null=True, verbose_name='Mandatory filters')),
                ('columns_exclude', models.JSONField(blank=True, default=list, help_text='Field paths to omit from import and from the example file. All other importable columns (top-level scalars and one FK level) are used. If a path is a forward relation (FK/O2O), all nested paths under that relation are excluded as well (e.g. author → author.name). Reverse-expand specs are not part of the default set.', null=True, verbose_name='Columns exclude')),
                ('exclude_primary_key', models.BooleanField(default=True, help_text='When enabled, the target model’s primary key field is omitted from the default column set (in addition to columns exclude).', verbose_name='Exclude primary key')),
                ('import_max_relation_hops', models.PositiveIntegerField(blank=True, help_text='Maximum number of relation hops in generated import paths (nested FKs, M2M slot paths such as tags.0.category.name). Use 0 for no nested relation paths (top-level columns only). Leave empty for no limit (a high internal cap applies).', null=True, verbose_name='Max relation hops')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Export options.', null=True, verbose_name='Configuration')),
                ('target', models.ForeignKey(blank=True, help_text='Listed model.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='django_importexport_flow_import_targeted', to='contenttypes.contenttype', verbose_name='Target content type')),
            ],
            options={
                'verbose_name': 'Import definition',
                'verbose_name_plural': 'Import definitions',
                'db_table': 'django_reporting_reportimport',
                'ordering': ('name', 'target'),
            },
        ),
        migrations.CreateModel(
            name='ImportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', django_boosted.models.fields.AuditUserField(blank=True, default=None, editable=False, max_length=255, mode='created', null=True)),
                ('updated_by', django_boosted.models.fields.AuditUserField(blank=True, default=None, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('data_file', models.FileField(upload_to='report_import_asks/%Y/%m/', verbose_name='Uploaded file')),
                ('filter_payload', models.JSONField(blank=True, default=dict, help_text='Keys fr_get_* / fr_kw_* from the import wizard.', verbose_name='Filter form payload')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=16, verbose_name='Status')),
                ('imported_row_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Imported row count')),
                ('error_trace', models.TextField(blank=True, help_text='Traceback or per-row errors when status is failure.', verbose_name='Error trace')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('import_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_requests', to='django_importexport_flow.importdefinition', verbose_name='Import definition')),
                ('initiated_by', models.ForeignKey(blank=True, help_text='User who started the import (wizard or relaunch).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_requests', to=settings.AUTH_USER_MODEL, verbose_name='Initiated by')),
                ('relaunched_from', models.ForeignKey(blank=True, help_text='Previous request when this row was created by “Relaunch”.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relaunches', to='django_importexport_flow.importrequest', verbose_name='Relaunched from')),
            ],
            options={
                'verbose_name': 'Import request',
                'verbose_name_plural': 'Import requests',
                'db_table': 'django_reporting_reportimportask',
                'ordering': ('-created_at',),
            },
        ),
    ]
