# Generated by Django 6.0.4 on 2026-04-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_importexport_flow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportdefinition",
            name="delegate_method",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Optional dotted path resolved on the target model (e.g. "objects.run_export" for Model.objects.run_export). When set, the definition fully delegates to this callable, which receives every concrete definition field plus the filter payload as keyword arguments and must return (bytes, content_type, extension).',
                max_length=255,
                verbose_name="Delegate method",
            ),
        ),
        migrations.AddField(
            model_name="importdefinition",
            name="delegate_method",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Optional dotted path resolved on the target model (e.g. "objects.run_import" for Model.objects.run_import). When set, the definition fully delegates to this callable, which receives every concrete definition field plus the filter payload, the uploaded file and the user as keyword arguments and must return the same dict shape as process_import.',
                max_length=255,
                verbose_name="Delegate method",
            ),
        ),
    ]
