# Generated by Django 6.0.5 on 2026-05-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_importexport_flow', '0003_alter_exportconfigtable_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportconfigtable',
            name='configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Export options passed to pandas: keys ``csv``, ``excel``, ``json`` (see DataFrame.to_csv, to_excel, to_json). Default JSON uses orient=records. Optional ``annotation_columns``: list of names added only by ``QuerySet.annotate()`` (not ORM fields, JSON subpaths, or properties) so they may appear in ``columns``. For any column path in ``columns`` with no ORM verbose name (annotations, unknown paths, …), you may set ``<path>_label`` to the header text, e.g. ``author.total_books_label`` for path ``author.total_books``; for expand subfields, use ``<subfield>_label`` (e.g. ``pages_label``). Excel only — ``split_by``: field path or column label used to split the export into one worksheet per distinct value (e.g. ``{"split_by": "author__name"}``). Each sheet is named after the field value. Ignored for CSV and JSON.', null=True, verbose_name='Configuration'),
        ),
    ]
